# Generated by Django 4.0.6 on 2022-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('collections', models.CharField(max_length=30, verbose_name='collections')),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(upload_to='home-page_banner/', verbose_name='home page banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'main banner',
                'verbose_name_plural': 'main banners',
            },
        ),
    ]
