# Generated by Django 4.0.6 on 2022-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepagebannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannermodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='is active'),
        ),
    ]
