# Generated by Django 4.0.6 on 2022-07-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productbrandmodel_productcolormodel_productsizemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='sizes',
            new_name='size',
        ),
    ]
